[package]
name = "ctci-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
paste = "1.0.14"
gen_tests = { path = "src/gen_tests" }
extra = { path = "src/extra" }

[workspace]
members = [
    ".",
    "src/extra",
    "src/gen_tests",
]

[features]
demo = []

